config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "products#index"

  namespace :admin do
    resources :products do
      member do
        post :publish
        post :hide
      end
    end

    resources :orders

  end

  resources :users do
    member do
      post :admin
      post :user
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      post :checkout
    end
  end

  resources :cart_items do
    member do
      post :change_quantity
      post :clear
      post :add_item
      post :des_item
    end
  end

  resources :orders

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.quantity * cart_item.product.price
    end
    sum
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :product_lists

  validates :billing_name,     presence: true
  validates :billing_address,  presence: true
  validates :shipping_name,    presence: true
  validates :shipping_name,    presence: true

  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  mount_uploader :image, ImageUploader

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    is_admin
  end

  def admin!
    self.is_admin = true
    self.save
  end

  def user!
    self.is_admin = false
    self.save
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @product_lists = @order.product_lists
  end

  def edit
    @order = Order.find(params[:id])
    
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to admin_orders_path, notice:'Order update'
    else
      render :edit
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to admin_orders_path,  alert:'Order deleted'
  end

  private

  def order_params
    params.require(:order).permit(:total, :billing_name, :billing_address, :shipping_name, :shipping_address, :created_at, :user_id)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def admin_required
    if !current_user.admin?
      redirect_to "/"
    end
  end

  helper_method :current_cart

  def current_cart
    @current_cart ||= find_cart
  end

  private
  def find_cart
    cart = Cart.find_by(id: session[:cart_id])
    if cart.blank?
      cart = Cart.create
    end
    session[:cart_id] = cart.id
    return cart
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_filter :authenticate_user!, only: [:add_item, :des_item, :destroy]

  def add_item
    @cart_item = current_cart.cart_items.find(params[:id])
    @cart_item.quantity = @cart_item.quantity + 1
    @cart_item.save
    redirect_to :back
  end

  def des_item
    @cart_item = current_cart.cart_items.find(params[:id])
    @cart_item.quantity = @cart_item.quantity - 1
    @cart_item.save
    redirect_to :back
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    
    redirect_to :back
  end

  def change_quantity
    @cart_item = CartItem.find(params[:id])
    add0rMB = params[:add0rMB]
    if add0rMB == "+"
      quantity = @cart_item.product.quantity
      if quantity > @cart_item.quantity + 1
        @cart_item.quantity = @cart_item.quantity + 1
        @cart_item.save
      else
        flash[:alert] = "商品库存不足"
      end
    else
      if @cart_item.quantity > 1
        @cart_item.quantity = @cart_item.quantity - 1
        @cart_item.save
      end
    end
    redirect_to :back
  end

  def clear
    @cart = current_cart
    @cart.cart_items.destroy_all

    redirect_to :back
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def checkout
    @order = Order.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def show
    @order = Order.find_by_token(params[:id])
    @product_lists = @order.product_lists
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = current_cart.total_price

    if @order.save

      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order = @order
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.quantity = cart_item.quantity
        product_list.save
      end

      redirect_to order_path(@order.token)
    else
      render 'carts/checkout'
    end
  end

  private

  def order_params
    params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @products = Product.where(is_hidden:false).order("created_at DESC")
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if @product.quantity > 0
      @cart_item = CartItem.find_by(product_id: @product.id, cart_id: current_cart.id)
      if @cart_item
        flash[:alert] = "此商品已在购物车！"
      else
        current_cart.add_product_to_cart(@product)
        flash[:notice] = "成功加入购物车！"
      end

    else
      flash[:alert] = "商品缺货！"
    end
    redirect_to :back
  end


  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :image, :is_hidden)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :admin_required
    layout "admin"
    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy

      redirect_to admin_users_path, alert:'User deleted'
    end

    def admin
      @user = User.find(params[:id])
      @user.admin!
      redirect_to :back
    end

    def user
      @user = User.find(params[:id])
      @user.user!

      redirect_to :back
    end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def render_product_status(product)
    if product.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def render_is_admin(user)
     if user1.is_admin
       "Admin"
     else
       "User"
     end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/orders/index.html.erb
<table class="table table-boldered">
  <thead>
    <tr>
      <th>订单号</th>
      <th>更新时间</th>
      <th>订单状态</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td>
          <%= link_to(order.user_id, admin_order_path(order) )%>
        </td>
        <td>
          <%= order.created_at %>
        </td>
        <td>
        </td>
        <td>
          <%= link_to("Edit", edit_admin_order_path(order)) %>  |
          <%= link_to("destroy", admin_order_path(order), method: :delete, data:{confirm: "Are you sure?"}) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>订单明细</h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="50%"> 商品详情 </th>
          <th> 单价 </th>
          <th> 数量 </th>
          <th> 备注 </th>
          <th> 操作 </th>
        </tr>
      </thead>

      <tbody>
        <% @product_lists.each do |product_list| %>
          <tr>
            <td>
              <%= product_list.product_name %>
            </td>
            <td>
              <%= product_list.product_price %>
            </td>
            <td>
              <%= product_list.quantity %>
            </td>
            <td>

            </td>
            <td>
              <%= link_to("Edit", edit_admin_order_path(@order),  class: "btn btn-xs btn-info")%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">总计: <%= @order.total %> RMB</span>
    </div>
    <hr>

    <h2>寄送资讯</h2>

    <table class="table table-striped table-bordered">
      <tbody>
        <tr>
          <td>订购人</td>
        </tr>
        <tr>
          <td><%= @order.billing_name %> - <%= @order.billing_address %></td>
        </tr>
        <tr>
          <td>收件人</td>
        </tr>
        <tr>
          <td>
            <%= @order.shipping_name %> - <%= @order.shipping_address %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/index.html.erb
admin订单详情页

app/views/orders/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>订单明细</h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%"> 商品详情 </th>
          <th> 单价 </th>
        </tr>
      </thead>

      <tbody>
        <% @product_lists.each do |product_list| %>
          <tr>
            <td>
              <%= product_list.product_name %>
            </td>
            <td>
              <%= product_list.product_price %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">总计: <%= @order.total %> RMB</span>
    </div>
    <hr>

    <h2>寄送资讯</h2>

    <table class="table table-striped table-bordered">
      <tbody>
        <tr>
          <td>订购人</td>
        </tr>
        <tr>
          <td><%= @order.billing_name %> - <%= @order.billing_address %></td>
        </tr>
        <tr>
          <td>收件人</td>
        </tr>
        <tr>
          <td>
            <%= @order.shipping_name %> - <%= @order.shipping_address %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>