config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "products#index"

  namespace :admin do
    resources :products do
      member do
        post :publish
        post :hide
      end
    end

    resources :orders

  end

  resources :users do
    member do
      post :admin
      post :user
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      post :checkout
    end
  end

  resources :cart_items do
    member do
      post :change_quantity
      post :clear
      post :add_item
      post :des_item
    end
  end

  resources :orders

end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  mount_uploader :image, ImageUploader

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update (product_params)
      redirect_to admin_products_path, notice:'Update Success'
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path, alert:'Product deleted'
  end

  def publish
    @product = Product.find(params[:id])
    @product.publish!
    redirect_to :back
  end

  def hide
    @product = Product.find(params[:id])
    @product.hide!
    redirect_to :back
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :image, :is_hidden)

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @products = Product.where(is_hidden:false).order("created_at DESC")
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if @product.quantity > 0
      @cart_item = CartItem.find_by(product_id: @product.id, cart_id: current_cart.id)
      if @cart_item
        flash[:alert] = "此商品已在购物车！"
      else
        current_cart.add_product_to_cart(@product)
        flash[:notice] = "成功加入购物车！"
      end

    else
      flash[:alert] = "商品缺货！"
    end
    redirect_to :back
  end


  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :image, :is_hidden)

  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def render_product_status(product)
    if product.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
end

app/views/admin/products/edit.html.erb
<h1>Edit a product</h1>
<%= simple_form_for [:admin,@product] do |f| %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.input :quantity %>
<%= f.input :image %>
<%= f.input :is_hidden %>
<%= f.submit "Submit" %>
<% end %>

app/views/admin/products/index.html.erb
<div class="pull-right">
  <%= link_to("Add a product", new_admin_product_path, :class => "btn btn-default" )%>
</div>

<table class="table table-boldered">
  <% @products.each do |product| %>
    <tr>
      <td>
        <img src="<%=product.image.mobile %>" alt="" />
      </td>
      <td>
        <%= link_to(product.title, admin_product_path(product) )%>
      </td>
      <td>
        <%= link_to(product.price, admin_product_path(product) )%>
      </td>
      <td>
        <%= link_to(product.quantity, admin_product_path(product) )%>
      </td>
      <td>
        <%= link_to("Edit", edit_admin_product_path(product)) %>  |
        <%= link_to("destroy", admin_product_path(product), method: :delete, data:{confirm: "Are you sure?"}) %> |
        <% if product.is_hidden %>

          <%= link_to("Publish", publish_admin_product_path(product), method: :post, class: "btn btn-xs btn-default") %>
        <% else %>
          <%= link_to("Hide", hide_admin_product_path(product), method: :post, class: "btn btn-xs btn-default") %>
        <% end %>

      </td>
      <td>
        <%= product.created_at%>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/products/new.html.erb
<h1>Add a product</h1>
<%=simple_form_for [:admin,@product] do |f| %>
<%= f.input :title %>
<%= f.input :image, label: "产品图片"%>
<%= f.input :description %>
<%= f.input :price %>
<%= f.input :quantity %>
<%= f.input :is_hidden %>
<%= f.submit "Submit" %>
<% end %>

app/views/admin/products/show.html.erb
<h1><%= @product.title %></h1>
<p>
  <img src="<%=@product.image.medium %>" alt=""/>
  <%= @product.description %>
  <%= @product.price %>
  <%= @product.quantity %>
</p>