config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "products#index"

  namespace :admin do
    resources :products do
      member do
        post :publish
        post :hide
      end
    end

    resources :orders

  end

  resources :users do
    member do
      post :admin
      post :user
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      post :checkout
    end
  end

  resources :cart_items do
    member do
      post :change_quantity
      post :clear
      post :add_item
      post :des_item
    end
  end

  resources :orders

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.quantity * cart_item.product.price
    end
    sum
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :product_lists

  validates :billing_name,     presence: true
  validates :billing_address,  presence: true
  validates :shipping_name,    presence: true
  validates :shipping_name,    presence: true

  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  mount_uploader :image, ImageUploader

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    is_admin
  end

  def admin!
    self.is_admin = true
    self.save
  end

  def user!
    self.is_admin = false
    self.save
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def checkout
    @order = Order.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def show
    @order = Order.find_by_token(params[:id])
    @product_lists = @order.product_lists
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = current_cart.total_price

    if @order.save

      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order = @order
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.quantity = cart_item.quantity
        product_list.save
      end

      redirect_to order_path(@order.token)
    else
      render 'carts/checkout'
    end
  end

  private

  def order_params
    params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @products = Product.where(is_hidden:false).order("created_at DESC")
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if @product.quantity > 0
      @cart_item = CartItem.find_by(product_id: @product.id, cart_id: current_cart.id)
      if @cart_item
        flash[:alert] = "此商品已在购物车！"
      else
        current_cart.add_product_to_cart(@product)
        flash[:notice] = "成功加入购物车！"
      end

    else
      flash[:alert] = "商品缺货！"
    end
    redirect_to :back
  end


  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :image, :is_hidden)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :admin_required
    layout "admin"
    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy

      redirect_to admin_users_path, alert:'User deleted'
    end

    def admin
      @user = User.find(params[:id])
      @user.admin!
      redirect_to :back
    end

    def user
      @user = User.find(params[:id])
      @user.user!

      redirect_to :back
    end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def render_product_status(product)
    if product.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def render_is_admin(user)
     if user1.is_admin
       "Admin"
     else
       "User"
     end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>
        <%= value %>
      </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top:100px">
  <p class="text-center">Copyright ©2016 xieping-store
    <br/>Design by
      <a href="#" target=_new>pigxie</a>
  </p>
</footer>
    

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!--Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">xieping-store</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to carts_path do %>
            购物车<i class="fa fa-shopping-cart"></i> (<%= current_cart.products.count %>)
          <% end %>
        </li>
        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %></li>
          <li><%= link_to("登入", new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hey!<%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
              <li><%= link_to("Admin Panel", admin_products_path) %></li>
              <% end %>
              <li><%= link_to("登出", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.comtainer-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>xieping-store</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
  </head>
  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
            <li class="active"><%= link_to("Products",admin_products_path )%></li>
          </ul>
          <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
            <li class="active"><%= link_to("Users", users_path )%></li>
          </ul>
          <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
              <li class="active"><%= link_to("Orders", admin_orders_path )%></li>
          </ul>
        </div>
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>

    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xieping-Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    <%= render"common/footer" %>
  </body>
</html>